name: sition
description: Sition, the Spotify to Youtube Music Converter

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  shared_preferences: ^2.0.5
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.0.8
  html_unescape: ^2.0.0
  google_sign_in: ^5.0.7
  youtube_api: ^1.0.4
  yt: ^2.2.1
  injectable: ^1.2.2
  get_it: ^6.0.0
  spotify_sdk: ^3.0.0-dev.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
